// <auto-generated />
namespace Infraestructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class v1_Create_People : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v1_Create_People));
        
        string IMigrationMetadata.Id
        {
            get { return "202206150121244_v1_Create_People"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
